// Somm — wine style knowledge base.
// Attribute vectors are 0–1: body, sweet, acid, tannin, fruit, oak.
// price = typical retail band in USD/EUR; restaurant ≈ 2.5x.
"use strict";

const WINES = [
  // ============ REDS ============
  { id: "pinot-burgundy", name: "Pinot Noir", region: "Burgundy, France", type: "red", grape: "Pinot Noir",
    attrs: { body: .40, sweet: .05, acid: .75, tannin: .35, fruit: .55, oak: .35 }, price: [20, 60],
    pairs: ["salmon", "duck", "mushroom", "chicken", "pork", "turkey"],
    desc: "Silky, red-cherry elegance — the wine that pairs with almost everything." },
  { id: "pinot-newworld", name: "Pinot Noir", region: "Oregon / New Zealand", type: "red", grape: "Pinot Noir",
    attrs: { body: .45, sweet: .10, acid: .65, tannin: .35, fruit: .70, oak: .30 }, price: [15, 45],
    pairs: ["salmon", "duck", "mushroom", "chicken", "pizza"],
    desc: "Juicier, fruitier cousin of Burgundy. Friendly and reliable." },
  { id: "cab-sauv", name: "Cabernet Sauvignon", region: "Napa / Bordeaux Left Bank", type: "red", grape: "Cabernet Sauvignon",
    attrs: { body: .90, sweet: .05, acid: .55, tannin: .90, fruit: .60, oak: .75 }, price: [18, 80],
    pairs: ["steak", "lamb", "burger", "hard cheese", "bbq"],
    desc: "Big, structured, cassis and cedar. The steakhouse classic." },
  { id: "merlot", name: "Merlot", region: "Bordeaux Right Bank / Chile", type: "red", grape: "Merlot",
    attrs: { body: .65, sweet: .10, acid: .50, tannin: .55, fruit: .70, oak: .50 }, price: [12, 40],
    pairs: ["roast chicken", "pork", "pasta", "burger", "pizza"],
    desc: "Plush plummy red without the tannic bite. Crowd-pleaser." },
  { id: "syrah-rhone", name: "Syrah", region: "Northern Rhône, France", type: "red", grape: "Syrah",
    attrs: { body: .80, sweet: .05, acid: .55, tannin: .70, fruit: .55, oak: .50 }, price: [20, 70],
    pairs: ["lamb", "steak", "bbq", "sausage", "stew"],
    desc: "Savory, peppery, black olive and smoke. For people who like edges." },
  { id: "shiraz", name: "Shiraz", region: "Barossa, Australia", type: "red", grape: "Shiraz",
    attrs: { body: .90, sweet: .20, acid: .45, tannin: .65, fruit: .90, oak: .65 }, price: [12, 45],
    pairs: ["bbq", "burger", "ribs", "steak"],
    desc: "Bold, jammy, unapologetic. Sunshine in a glass." },
  { id: "malbec", name: "Malbec", region: "Mendoza, Argentina", type: "red", grape: "Malbec",
    attrs: { body: .80, sweet: .15, acid: .50, tannin: .60, fruit: .85, oak: .55 }, price: [10, 35],
    pairs: ["steak", "bbq", "burger", "empanadas", "lamb"],
    desc: "Velvety dark fruit, soft tannin, serious value. Steak's best friend." },
  { id: "rioja", name: "Rioja Reserva", region: "Rioja, Spain", type: "red", grape: "Tempranillo",
    attrs: { body: .65, sweet: .05, acid: .60, tannin: .55, fruit: .55, oak: .75 }, price: [15, 45],
    pairs: ["lamb", "jamón", "tapas", "roast chicken", "hard cheese", "stew"],
    desc: "Vanilla, leather, dried cherry — oak-aged elegance at honest prices." },
  { id: "chianti", name: "Chianti Classico", region: "Tuscany, Italy", type: "red", grape: "Sangiovese",
    attrs: { body: .60, sweet: .05, acid: .80, tannin: .65, fruit: .55, oak: .40 }, price: [14, 45],
    pairs: ["pasta", "pizza", "tomato", "salami", "lasagna", "burger"],
    desc: "Bright cherry and herbs with mouthwatering acidity. Born for tomato sauce." },
  { id: "barolo", name: "Barolo", region: "Piedmont, Italy", type: "red", grape: "Nebbiolo",
    attrs: { body: .75, sweet: .05, acid: .80, tannin: .95, fruit: .45, oak: .50 }, price: [35, 120],
    pairs: ["truffle", "risotto", "braised beef", "mushroom", "hard cheese"],
    desc: "Tar and roses. Demanding, profound, unforgettable — a wine to respect." },
  { id: "valpolicella", name: "Valpolicella Ripasso", region: "Veneto, Italy", type: "red", grape: "Corvina blend",
    attrs: { body: .65, sweet: .20, acid: .60, tannin: .50, fruit: .75, oak: .45 }, price: [15, 35],
    pairs: ["pasta", "pizza", "risotto", "pork", "stew"],
    desc: "Baby Amarone — raisined richness without the price tag." },
  { id: "amarone", name: "Amarone della Valpolicella", region: "Veneto, Italy", type: "red", grape: "Corvina blend",
    attrs: { body: .95, sweet: .30, acid: .55, tannin: .70, fruit: .85, oak: .60 }, price: [40, 100],
    pairs: ["braised beef", "stew", "aged cheese", "game"],
    desc: "Dried-grape opulence. A fireplace wine for big nights." },
  { id: "cotes-du-rhone", name: "Côtes-du-Rhône", region: "Southern Rhône, France", type: "red", grape: "Grenache blend",
    attrs: { body: .65, sweet: .10, acid: .55, tannin: .50, fruit: .70, oak: .30 }, price: [10, 25],
    pairs: ["roast chicken", "stew", "sausage", "pizza", "weeknight"],
    desc: "The great-value weeknight red. Warm spice and easy charm." },
  { id: "chateauneuf", name: "Châteauneuf-du-Pape", region: "Southern Rhône, France", type: "red", grape: "Grenache blend",
    attrs: { body: .85, sweet: .10, acid: .55, tannin: .65, fruit: .75, oak: .40 }, price: [35, 90],
    pairs: ["lamb", "game", "stew", "duck", "hard cheese"],
    desc: "Garrigue herbs, ripe berries, quiet power. Special-occasion Rhône." },
  { id: "beaujolais", name: "Beaujolais (Cru)", region: "Beaujolais, France", type: "red", grape: "Gamay",
    attrs: { body: .35, sweet: .10, acid: .75, tannin: .30, fruit: .85, oak: .15 }, price: [12, 30],
    pairs: ["charcuterie", "chicken", "salmon", "picnic", "thanksgiving", "turkey"],
    desc: "Chillable, crunchy red fruit, pure joy. Serve it cool, drink it fast." },
  { id: "zinfandel", name: "Zinfandel", region: "California, USA", type: "red", grape: "Zinfandel",
    attrs: { body: .80, sweet: .25, acid: .50, tannin: .55, fruit: .90, oak: .50 }, price: [12, 40],
    pairs: ["bbq", "ribs", "burger", "pizza"],
    desc: "Brambly jam and black pepper. America's BBQ wine." },
  { id: "primitivo", name: "Primitivo", region: "Puglia, Italy", type: "red", grape: "Primitivo",
    attrs: { body: .75, sweet: .30, acid: .45, tannin: .50, fruit: .90, oak: .40 }, price: [9, 25],
    pairs: ["pizza", "bbq", "pasta", "sausage", "weeknight"],
    desc: "Sun-soaked, plush, faintly sweet. Maximum comfort per euro." },
  { id: "carmenere", name: "Carménère", region: "Chile", type: "red", grape: "Carménère",
    attrs: { body: .70, sweet: .10, acid: .50, tannin: .55, fruit: .65, oak: .45 }, price: [10, 30],
    pairs: ["burger", "pork", "bbq", "stew", "roasted vegetables"],
    desc: "Dark fruit with a green-peppercorn twist. Chile's signature." },
  { id: "nero-davola", name: "Nero d'Avola", region: "Sicily, Italy", type: "red", grape: "Nero d'Avola",
    attrs: { body: .70, sweet: .15, acid: .55, tannin: .55, fruit: .80, oak: .35 }, price: [9, 22],
    pairs: ["pasta", "pizza", "eggplant", "lamb", "tomato"],
    desc: "Sicilian sunshine — ripe plum, soft edges, great value." },
  { id: "pinotage", name: "Pinotage", region: "South Africa", type: "red", grape: "Pinotage",
    attrs: { body: .75, sweet: .15, acid: .50, tannin: .60, fruit: .70, oak: .55 }, price: [10, 30],
    pairs: ["bbq", "game", "burger", "ribs"],
    desc: "Smoky, wild, divisive — the adventurous griller's red." },

  // ============ WHITES ============
  { id: "chablis", name: "Chablis", region: "Burgundy, France", type: "white", grape: "Chardonnay",
    attrs: { body: .45, sweet: .05, acid: .85, tannin: .05, fruit: .40, oak: .10 }, price: [18, 50],
    pairs: ["oyster", "seafood", "sushi", "goat cheese", "white fish"],
    desc: "Steely, saline, bone-dry Chardonnay. Oysters' soulmate." },
  { id: "chard-oaked", name: "Chardonnay (oaked)", region: "California / Côte de Beaune", type: "white", grape: "Chardonnay",
    attrs: { body: .75, sweet: .15, acid: .55, tannin: .05, fruit: .60, oak: .80 }, price: [15, 60],
    pairs: ["lobster", "roast chicken", "creamy pasta", "corn", "butter"],
    desc: "Butter, toast, ripe orchard fruit. Rich and embracing." },
  { id: "sauv-blanc-nz", name: "Sauvignon Blanc", region: "Marlborough, NZ", type: "white", grape: "Sauvignon Blanc",
    attrs: { body: .40, sweet: .10, acid: .90, tannin: .05, fruit: .80, oak: .05 }, price: [10, 25],
    pairs: ["goat cheese", "salad", "asparagus", "white fish", "thai", "ceviche"],
    desc: "Explosive passionfruit and cut grass. Impossible to mistake." },
  { id: "sancerre", name: "Sancerre", region: "Loire, France", type: "white", grape: "Sauvignon Blanc",
    attrs: { body: .40, sweet: .05, acid: .85, tannin: .05, fruit: .55, oak: .05 }, price: [20, 45],
    pairs: ["goat cheese", "salad", "white fish", "shellfish", "sushi"],
    desc: "Flinty, citrus-precise Loire Sauvignon. Quiet sophistication." },
  { id: "riesling-dry", name: "Riesling (dry)", region: "Alsace / Clare Valley", type: "white", grape: "Riesling",
    attrs: { body: .45, sweet: .10, acid: .90, tannin: .05, fruit: .65, oak: .05 }, price: [14, 40],
    pairs: ["thai", "sushi", "pork", "spicy", "vietnamese", "indian"],
    desc: "Lime-zest laser beam. The food-pairing Swiss army knife." },
  { id: "riesling-offdry", name: "Riesling (off-dry)", region: "Mosel, Germany", type: "white", grape: "Riesling",
    attrs: { body: .35, sweet: .45, acid: .90, tannin: .05, fruit: .75, oak: .05 }, price: [14, 45],
    pairs: ["spicy", "thai", "indian", "chinese", "pork", "blue cheese"],
    desc: "Sweet-tart tension — peach and slate. Magic with spicy food." },
  { id: "gruner", name: "Grüner Veltliner", region: "Austria", type: "white", grape: "Grüner Veltliner",
    attrs: { body: .45, sweet: .05, acid: .80, tannin: .05, fruit: .50, oak: .10 }, price: [12, 35],
    pairs: ["schnitzel", "salad", "asparagus", "sushi", "vegetables"],
    desc: "White pepper and green apple. The sommelier's house white." },
  { id: "albarino", name: "Albariño", region: "Rías Baixas, Spain", type: "white", grape: "Albariño",
    attrs: { body: .45, sweet: .05, acid: .80, tannin: .05, fruit: .65, oak: .05 }, price: [12, 30],
    pairs: ["seafood", "shellfish", "ceviche", "paella", "white fish"],
    desc: "Sea-spray freshness with peachy charm. Built for seafood." },
  { id: "pinot-grigio", name: "Pinot Grigio", region: "Alto Adige, Italy", type: "white", grape: "Pinot Grigio",
    attrs: { body: .40, sweet: .05, acid: .70, tannin: .05, fruit: .45, oak: .05 }, price: [9, 22],
    pairs: ["salad", "white fish", "antipasti", "light pasta", "aperitif"],
    desc: "Clean, crisp, no drama. The reliable porch-pounder." },
  { id: "pinot-gris", name: "Pinot Gris", region: "Alsace, France", type: "white", grape: "Pinot Gris",
    attrs: { body: .65, sweet: .30, acid: .55, tannin: .05, fruit: .70, oak: .15 }, price: [15, 40],
    pairs: ["pork", "duck", "creamy pasta", "soft cheese", "tarte flambée"],
    desc: "Honeyed pear with weight — Pinot Grigio's serious sibling." },
  { id: "gewurz", name: "Gewürztraminer", region: "Alsace, France", type: "white", grape: "Gewürztraminer",
    attrs: { body: .65, sweet: .40, acid: .45, tannin: .05, fruit: .85, oak: .10 }, price: [15, 40],
    pairs: ["indian", "thai", "spicy", "munster", "duck", "asian"],
    desc: "Lychee, rose petals, exotic spice. Love-it-or-leave-it perfume." },
  { id: "viognier", name: "Viognier", region: "Condrieu / California", type: "white", grape: "Viognier",
    attrs: { body: .70, sweet: .20, acid: .45, tannin: .05, fruit: .80, oak: .35 }, price: [14, 50],
    pairs: ["roast chicken", "lobster", "apricot", "soft cheese", "curry"],
    desc: "Apricot and honeysuckle opulence. Rich without sweetness." },
  { id: "chenin", name: "Chenin Blanc", region: "Loire / South Africa", type: "white", grape: "Chenin Blanc",
    attrs: { body: .55, sweet: .25, acid: .80, tannin: .05, fruit: .65, oak: .20 }, price: [10, 35],
    pairs: ["pork", "chicken", "thai", "soft cheese", "salad"],
    desc: "Quince and honey over bright acid. Criminally underrated." },
  { id: "vermentino", name: "Vermentino", region: "Sardinia / Liguria, Italy", type: "white", grape: "Vermentino",
    attrs: { body: .45, sweet: .05, acid: .75, tannin: .05, fruit: .55, oak: .05 }, price: [10, 25],
    pairs: ["seafood", "pesto", "white fish", "antipasti", "salad"],
    desc: "Mediterranean herbs and salt air. Coastal lunch in a bottle." },
  { id: "assyrtiko", name: "Assyrtiko", region: "Santorini, Greece", type: "white", grape: "Assyrtiko",
    attrs: { body: .55, sweet: .05, acid: .90, tannin: .10, fruit: .45, oak: .10 }, price: [16, 40],
    pairs: ["grilled fish", "octopus", "feta", "greek", "seafood"],
    desc: "Volcanic, electric, mineral. Greece's world-class secret." },

  // ============ ROSÉ ============
  { id: "provence-rose", name: "Provence Rosé", region: "Provence, France", type: "rose", grape: "Grenache blend",
    attrs: { body: .35, sweet: .05, acid: .70, tannin: .10, fruit: .55, oak: .05 }, price: [12, 30],
    pairs: ["salad", "picnic", "seafood", "aperitif", "niçoise", "summer"],
    desc: "Pale, dry, effortless. Summer's official wine." },
  { id: "tavel", name: "Tavel Rosé", region: "Rhône, France", type: "rose", grape: "Grenache blend",
    attrs: { body: .55, sweet: .10, acid: .65, tannin: .25, fruit: .70, oak: .05 }, price: [14, 30],
    pairs: ["bbq", "charcuterie", "paella", "grilled chicken", "burger"],
    desc: "The rosé that thinks it's a red. Gastronomic and serious." },

  // ============ SPARKLING ============
  { id: "champagne", name: "Champagne (Brut)", region: "Champagne, France", type: "sparkling", grape: "Chard/Pinot blend",
    attrs: { body: .50, sweet: .10, acid: .85, tannin: .05, fruit: .45, oak: .25 }, price: [35, 90],
    pairs: ["celebration", "oyster", "fried chicken", "sushi", "chips", "everything"],
    desc: "Brioche, citrus, tiny bubbles, big occasion. Also elite with fried food." },
  { id: "cremant", name: "Crémant (Bourgogne/Loire)", region: "France", type: "sparkling", grape: "varies",
    attrs: { body: .45, sweet: .10, acid: .80, tannin: .05, fruit: .50, oak: .15 }, price: [13, 28],
    pairs: ["aperitif", "celebration", "fried", "brunch", "sushi"],
    desc: "Champagne method, half the price. The insider's bubbles." },
  { id: "cava", name: "Cava (Reserva)", region: "Penedès, Spain", type: "sparkling", grape: "Xarel·lo blend",
    attrs: { body: .45, sweet: .10, acid: .75, tannin: .05, fruit: .50, oak: .15 }, price: [9, 22],
    pairs: ["tapas", "aperitif", "fried", "brunch", "jamón"],
    desc: "Honest, toasty fizz at a price that makes Tuesday a celebration." },
  { id: "prosecco", name: "Prosecco (Brut)", region: "Veneto, Italy", type: "sparkling", grape: "Glera",
    attrs: { body: .35, sweet: .25, acid: .65, tannin: .05, fruit: .70, oak: .05 }, price: [9, 20],
    pairs: ["aperitif", "brunch", "spritz", "light bites", "celebration"],
    desc: "Pear and white flowers, easy bubbles. Aperitivo hour, always." },
  { id: "franciacorta", name: "Franciacorta", region: "Lombardy, Italy", type: "sparkling", grape: "Chard/Pinot blend",
    attrs: { body: .55, sweet: .10, acid: .80, tannin: .05, fruit: .50, oak: .25 }, price: [25, 55],
    pairs: ["risotto", "seafood", "celebration", "aperitif", "fried"],
    desc: "Italy's answer to Champagne — creamy, refined, still under-the-radar." },
  { id: "lambrusco", name: "Lambrusco (dry)", region: "Emilia-Romagna, Italy", type: "sparkling", grape: "Lambrusco",
    attrs: { body: .50, sweet: .25, acid: .65, tannin: .35, fruit: .80, oak: .05 }, price: [10, 20],
    pairs: ["pizza", "salami", "charcuterie", "lasagna", "parmesan"],
    desc: "Chilled, frothy purple joy. Cured meat's favorite wine." },

  // ============ ORANGE / SKIN-CONTACT ============
  { id: "orange-wine", name: "Orange / Skin-contact White", region: "Georgia / Friuli / Slovenia", type: "orange", grape: "varies",
    attrs: { body: .65, sweet: .05, acid: .70, tannin: .50, fruit: .60, oak: .25 }, price: [15, 45],
    pairs: ["fermented", "korean", "curry", "hard cheese", "charcuterie", "adventurous"],
    desc: "White grapes, red technique — tea, apricot, gentle grip. For the curious." },

  // ============ DESSERT / FORTIFIED ============
  { id: "sauternes", name: "Sauternes", region: "Bordeaux, France", type: "dessert", grape: "Sémillon blend",
    attrs: { body: .75, sweet: .90, acid: .65, tannin: .05, fruit: .85, oak: .40 }, price: [25, 80],
    pairs: ["blue cheese", "foie gras", "dessert", "fruit tart", "crème brûlée"],
    desc: "Liquid gold — honey, apricot, eternity. Roquefort's dance partner." },
  { id: "port", name: "Port (Ruby/LBV)", region: "Douro, Portugal", type: "dessert", grape: "Touriga blend",
    attrs: { body: .95, sweet: .85, acid: .50, tannin: .70, fruit: .90, oak: .45 }, price: [15, 50],
    pairs: ["chocolate", "blue cheese", "dessert", "nuts", "fireplace"],
    desc: "Dark chocolate-soaked berries with a warm hug of strength." },
  { id: "moscato", name: "Moscato d'Asti", region: "Piedmont, Italy", type: "dessert", grape: "Moscato",
    attrs: { body: .25, sweet: .80, acid: .60, tannin: .05, fruit: .95, oak: .05 }, price: [10, 20],
    pairs: ["fruit", "dessert", "brunch", "cake", "spicy"],
    desc: "Gently fizzy grape-blossom sweetness at 5%. Pure innocence." },
  { id: "sherry-fino", name: "Fino / Manzanilla Sherry", region: "Jerez, Spain", type: "white", grape: "Palomino",
    attrs: { body: .45, sweet: .02, acid: .70, tannin: .05, fruit: .25, oak: .30 }, price: [10, 25],
    pairs: ["almonds", "olives", "jamón", "tapas", "sushi", "fried fish"],
    desc: "Bone-dry, saline, bracing. The most food-friendly wine nobody orders." },
];

// Food keyword → boost map used by the local pairing engine.
// Keys are lowercase fragments matched against the user's food text.
const FOOD_SYNONYMS = {
  steak: ["steak", "beef", "ribeye", "entrecote", "filet", "sirloin"],
  lamb: ["lamb", "kebab", "shawarma"],
  burger: ["burger", "hamburger"],
  bbq: ["bbq", "barbecue", "grilled meat", "grilled steak", "ribs", "brisket", "asado"],
  stew: ["stew", "braise", "braised", "cholent", "goulash", "tagine"],
  pork: ["pork", "schnitzel", "tonkatsu", "bacon"],
  chicken: ["chicken", "poultry", "roast chicken", "schnitzel"],
  turkey: ["turkey", "thanksgiving"],
  duck: ["duck", "foie"],
  game: ["venison", "game", "wild boar"],
  salmon: ["salmon", "tuna", "trout", "grilled fish"],
  "white fish": ["fish", "cod", "halibut", "branzino", "sea bass", "dover", "tilapia"],
  seafood: ["seafood", "shrimp", "prawn", "crab", "lobster", "mussels", "clams", "calamari", "octopus", "scallop", "paella"],
  oyster: ["oyster"],
  sushi: ["sushi", "sashimi", "poke", "japanese"],
  ceviche: ["ceviche", "crudo", "tartare"],
  pasta: ["pasta", "spaghetti", "carbonara", "bolognese", "ragu", "gnocchi"],
  "creamy pasta": ["alfredo", "carbonara", "cream sauce", "mac and cheese"],
  tomato: ["tomato", "marinara", "pomodoro", "shakshuka"],
  pizza: ["pizza"],
  lasagna: ["lasagna", "lasagne"],
  risotto: ["risotto"],
  mushroom: ["mushroom", "truffle", "porcini"],
  spicy: ["spicy", "chili", "sichuan", "szechuan", "harissa", "jalapeno"],
  thai: ["thai", "pad thai", "green curry"],
  indian: ["indian", "curry", "tikka", "masala", "biryani"],
  chinese: ["chinese", "dim sum", "dumpling", "noodles", "stir fry", "stir-fry"],
  korean: ["korean", "kimchi", "bibimbap", "korean bbq"],
  vietnamese: ["vietnamese", "pho", "banh mi"],
  asian: ["asian"],
  greek: ["greek", "souvlaki", "gyro"],
  feta: ["feta", "halloumi"],
  tapas: ["tapas", "spanish"],
  jamón: ["jamon", "jamón", "iberico", "prosciutto", "serrano"],
  charcuterie: ["charcuterie", "salami", "cured meat", "cold cuts"],
  salad: ["salad", "greens", "caesar"],
  vegetables: ["vegetable", "veggie", "vegan", "vegetarian", "roasted vegetables", "eggplant", "aubergine", "cauliflower"],
  asparagus: ["asparagus", "artichoke"],
  "goat cheese": ["goat cheese", "chevre", "chèvre"],
  "soft cheese": ["brie", "camembert", "soft cheese", "burrata", "mozzarella"],
  "hard cheese": ["cheddar", "parmesan", "gouda", "manchego", "hard cheese", "gruyere", "comte", "cheese board", "cheese"],
  "blue cheese": ["blue cheese", "roquefort", "gorgonzola", "stilton"],
  fried: ["fried", "tempura", "fried chicken", "fish and chips", "falafel", "fries"],
  brunch: ["brunch", "eggs", "omelette", "quiche"],
  picnic: ["picnic", "sandwich"],
  aperitif: ["aperitif", "apero", "snacks", "nibbles", "olives", "nuts", "chips"],
  celebration: ["celebration", "birthday", "anniversary", "party", "toast", "new year"],
  chocolate: ["chocolate", "brownie"],
  dessert: ["dessert", "cake", "tart", "ice cream", "pavlova", "tiramisu", "sweet"],
  fruit: ["fruit", "peach", "berries", "melon"],
  fermented: ["fermented", "funky", "natural"],
  weeknight: ["weeknight", "casual", "easy", "nothing special", "tuesday"],
  summer: ["summer", "hot day", "beach", "pool", "terrace", "balcony"],
};

// Onboarding quiz. Each option applies deltas to profile dims / types / adventure.
const QUIZ = [
  {
    id: "coffee", q: "How do you take your coffee?",
    sub: "No wrong answers — this tells me about bitterness.",
    options: [
      { label: "Black, always", fx: { dims: { tannin: +.20, oak: +.05, sweet: -.10 } } },
      { label: "With milk", fx: { dims: { body: +.05 } } },
      { label: "Milk and sugar", fx: { dims: { sweet: +.15, tannin: -.10 } } },
      { label: "I don't drink coffee", fx: { dims: { tannin: -.05 } } },
    ],
  },
  {
    id: "chocolate", q: "Pick a chocolate:",
    sub: "Bitterness check, round two.",
    options: [
      { label: "85% dark", fx: { dims: { tannin: +.20, sweet: -.15, body: +.05 } } },
      { label: "Classic milk", fx: { dims: { sweet: +.10, tannin: -.05 } } },
      { label: "White chocolate", fx: { dims: { sweet: +.20, tannin: -.15 } } },
      { label: "Salted caramel anything", fx: { dims: { sweet: +.15, fruit: +.05 } } },
    ],
  },
  {
    id: "hotday", q: "It's a hot day. What are you reaching for?",
    sub: "This one's about acidity.",
    options: [
      { label: "Ice-cold lemonade", fx: { dims: { acid: +.20, fruit: +.05 } } },
      { label: "Sparkling water with lime", fx: { dims: { acid: +.15, sweet: -.10 }, types: { sparkling: +.15 } } },
      { label: "Sweet iced tea", fx: { dims: { sweet: +.20, acid: -.05 } } },
      { label: "Cold beer", fx: { dims: { tannin: +.05, sweet: -.05 } } },
    ],
  },
  {
    id: "dinner", q: "Dream dinner tonight — pick one:",
    sub: "Food tells me a lot about wine.",
    options: [
      { label: "Ribeye off the grill", fx: { dims: { body: +.20, tannin: +.15, oak: +.10 }, types: { red: +.25 } } },
      { label: "Sushi omakase", fx: { dims: { acid: +.15, body: -.15 }, types: { white: +.20, sparkling: +.10 } } },
      { label: "Handmade pasta al pomodoro", fx: { dims: { acid: +.15, fruit: +.05 }, types: { red: +.15 } } },
      { label: "Spicy Thai feast", fx: { dims: { sweet: +.15, acid: +.10, body: -.10 }, types: { white: +.20 } } },
      { label: "A great cheese board", fx: { dims: { body: +.05, oak: +.05 }, types: { red: +.10, white: +.05 } } },
    ],
  },
  {
    id: "gut", q: "Gut feeling — what's your wine?",
    sub: "Even if you're not sure. First instinct.",
    options: [
      { label: "Red", fx: { types: { red: +.35 }, dims: { body: +.10, tannin: +.10 } } },
      { label: "White", fx: { types: { white: +.35 }, dims: { acid: +.10, body: -.10 } } },
      { label: "Rosé", fx: { types: { rose: +.35 }, dims: { acid: +.10, body: -.10 } } },
      { label: "Bubbles", fx: { types: { sparkling: +.35 }, dims: { acid: +.10 } } },
      { label: "Honestly, no idea — surprise me", fx: { adventure: +.15 } },
    ],
  },
  {
    id: "experience", q: "Where are you on the wine journey?",
    sub: "So I know how much to explain.",
    options: [
      { label: "Just starting out", fx: { experience: "beginner" } },
      { label: "I know what I like", fx: { experience: "casual" } },
      { label: "Enthusiast — I read labels", fx: { experience: "enthusiast", adventure: +.05 } },
      { label: "Full wine nerd", fx: { experience: "nerd", adventure: +.10 } },
    ],
  },
  {
    id: "adventure", q: "Same trusted bottle, or something new every time?",
    sub: "Adventure calibration.",
    options: [
      { label: "My favorites, please", fx: { adventure: -.20 } },
      { label: "Mostly favorites, sometimes new", fx: { adventure: 0 } },
      { label: "Mostly new, keep it interesting", fx: { adventure: +.20 } },
      { label: "Never the same wine twice", fx: { adventure: +.35 } },
    ],
  },
  {
    id: "budget", q: "What do you usually spend on a bottle at the store?",
    sub: "I'll keep recommendations honest. Restaurant budget scales automatically — you can fine-tune later.",
    options: [
      { label: "Under 12", fx: { budget: [6, 12] } },
      { label: "12–25", fx: { budget: [12, 25] } },
      { label: "25–50", fx: { budget: [25, 50] } },
      { label: "Sky's the limit", fx: { budget: [25, 150] } },
    ],
  },
  {
    id: "nos", q: "Any hard nos?",
    sub: "Pick all that apply — I'll never recommend these.", multi: true,
    options: [
      { label: "No sweet wines", fx: { no: "sweet" } },
      { label: "No heavy oaky wines", fx: { no: "oak" } },
      { label: "No reds", fx: { no: "red" } },
      { label: "No whites", fx: { no: "white" } },
      { label: "No bubbles", fx: { no: "sparkling" } },
      { label: "Nope — everything's on the table", fx: {} },
    ],
  },
];

// Restaurant cheat-sheet for offline mode.
const RESTO_CHEATSHEET = [
  { cuisine: "Italian", tip: "Chianti Classico or Barbera with anything tomato; Vermentino or Pinot Grigio with seafood; Lambrusco with salumi." },
  { cuisine: "French bistro", tip: "Côtes-du-Rhône with steak frites; Chablis or Sancerre with fish; Cru Beaujolais covers the whole table." },
  { cuisine: "Steakhouse", tip: "Cabernet, Malbec, or Rioja Reserva. If the list is fancy, Châteauneuf-du-Pape over-delivers." },
  { cuisine: "Sushi / Japanese", tip: "Champagne or dry Riesling. Chablis if they have it. Avoid big oaky reds at all costs." },
  { cuisine: "Thai / spicy Asian", tip: "Off-dry Riesling or Gewürztraminer — a touch of sweetness tames the heat. Avoid high-alcohol reds." },
  { cuisine: "Indian", tip: "Gewürztraminer, off-dry Riesling, or a juicy chillable red like Beaujolais. Skip tannic reds with spice." },
  { cuisine: "Seafood / Mediterranean", tip: "Albariño, Assyrtiko, Vermentino, Picpoul — anything coastal, crisp and saline." },
  { cuisine: "Middle Eastern", tip: "Rosé and lighter reds shine. Tavel with mixed mezze; Syrah with grilled lamb." },
  { cuisine: "Burgers / BBQ", tip: "Zinfandel, Shiraz, Malbec. Sparkling is the sleeper pick with anything fried." },
  { cuisine: "Vegetarian / salads", tip: "Grüner Veltliner and Sauvignon Blanc handle green things (even asparagus) best." },
];

const SOMM_DATA = { WINES, FOOD_SYNONYMS, QUIZ, RESTO_CHEATSHEET };
